"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateAppCheckToken = exports.serverSignOutUrl = exports.serverTokenUrl = exports.idTokenVerificationUrl = exports.baseUrl = exports.initialize = exports.logEvent = exports.verifyIdToken = exports.signOut = exports.signIn = void 0;
var auth_1 = require("./auth");
Object.defineProperty(exports, "signIn", { enumerable: true, get: function () { return auth_1.signIn; } });
Object.defineProperty(exports, "signOut", { enumerable: true, get: function () { return auth_1.signOut; } });
Object.defineProperty(exports, "verifyIdToken", { enumerable: true, get: function () { return auth_1.verifyIdToken; } });
var analytics_1 = require("./analytics");
Object.defineProperty(exports, "logEvent", { enumerable: true, get: function () { return analytics_1.logEvent; } });
let baseUrl;
let idTokenVerificationUrl;
let serverTokenUrl;
let serverSignOutUrl;
let generateAppCheckToken;
const initialize = (params) => {
    exports.baseUrl = baseUrl = params.baseUrl;
    exports.idTokenVerificationUrl = idTokenVerificationUrl = params.idTokenVerificationUrl;
    exports.serverTokenUrl = serverTokenUrl = params.serverTokenUrl;
    exports.serverSignOutUrl = serverSignOutUrl = params.serverSignOutUrl;
    exports.generateAppCheckToken = generateAppCheckToken = params.generateAppCheckToken;
};
exports.initialize = initialize;
