"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.logEvent = exports.getAppCheckToken = exports.serverSignOutUrl = exports.serverTokenUrl = exports.idTokenVerificationUrl = exports.baseUrl = exports.initializeJsFire = exports.verifyIdToken = exports.signOut = exports.signIn = void 0;
var auth_1 = require("./auth");
Object.defineProperty(exports, "signIn", { enumerable: true, get: function () { return auth_1.signIn; } });
Object.defineProperty(exports, "signOut", { enumerable: true, get: function () { return auth_1.signOut; } });
Object.defineProperty(exports, "verifyIdToken", { enumerable: true, get: function () { return auth_1.verifyIdToken; } });
let baseUrl;
let idTokenVerificationUrl;
let serverTokenUrl;
let serverSignOutUrl;
let getAppCheckToken;
let logEvent;
const initializeJsFire = (options) => {
    exports.baseUrl = baseUrl = options.baseUrl;
    exports.idTokenVerificationUrl = idTokenVerificationUrl = options.idTokenVerificationUrl;
    exports.serverTokenUrl = serverTokenUrl = options.serverTokenUrl;
    exports.serverSignOutUrl = serverSignOutUrl = options.serverSignOutUrl;
    exports.getAppCheckToken = getAppCheckToken = options.getAppCheckToken;
    exports.logEvent = logEvent = options.logEvent;
};
exports.initializeJsFire = initializeJsFire;
